import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Sidebar from "@/components/layouts/sidebar"; // Sidebar component
import {NavigationMenuDemo} from "@/components/layouts/nav"; // Navbar component

export const metadata: Metadata = {
  title: "Inventory Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <ThemeProvider attribute="class">
          <div className="flex h-screen">
            <aside className="w-64">
              <Sidebar />
            </aside>

            <div className="flex flex-col flex-1">
              <header className="h-16">
                <NavigationMenuDemo />
              </header>

              <main className="flex-1">{children}</main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
